### ISSUE TITLE
Bug when resetting game, the grade stays the same after resetting the game

### ISSUE THREAD

**Issue by RachelleBadua** [Doreen03/Lola-s-Learning#2]
Hey, I noticed after you reset the game that you get the same grade from the last game you play.

-You play the game until the monster comes 
-Then you reset to the main menu and play the game again
-The same grade you have from the last game you played is still there, instead of having a 100% as the grade

You can fix if you have time 

- Rachelle Badua

**Comment by GoldyBlocksLOL** [comment]
Fixed it

**Comment by GoldyBlocksLOL** [comment]
Nevermind, Doreen wasn't able to fix it and now the whole scoreboard isn't working.

**Comment by GoldyBlocksLOL** [comment]
Nevermind, fixed it again
