### ISSUE TITLE
Bug: Game ends when walking off level

### ISSUE THREAD

**Issue by steve2142838** [Doreen03/Lola-s-Learning#4]
no boundaries for the top part of the world, resulting in the game stopping when you walk past it

![image](https://user-images.githubusercontent.com/89649666/145488619-cb6f4694-6bef-4c74-a98f-00336a445fe1.png)

- Steve Nguyen

**Comment by GoldyBlocksLOL** [comment]
Thanks for letting us know about this issue!

I was already aware of there not being any boundaries in the hallway world, so when we add it we'll update you. You were saying the game ended when you walked outside of the world?

**Comment by GoldyBlocksLOL** [comment]
Issue has been fixed!
