### ISSUE TITLE
The same issue as stated by badua Rachelle( Stuck on the same level)

### ISSUE THREAD

**Issue by Ramanantrm** [Doreen03/Lola-s-Learning#6]
Hi, I have also noticed that when you reset the game you end up being stuck on the same level. It was the end where you're being chased by the monster and clicking reset doesn't change anything.

-Ramanan Thirugnanasundaram

**Comment by GoldyBlocksLOL** [comment]
Can it be possible that you were running the game while it was on the "FinalLevel" world? To start the game, you should probably right click the "MainMenu" class and choose "new MainMenu()"
